// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sarona.Models;

namespace Sarona.Migrations
{
    [DbContext(typeof(SaronaContext))]
    [Migration("13970903101612_Scripts")]
    partial class Scripts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.AccessSequence", "'AccessSequence', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.PbxSequence", "'PbxSequence', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.RemoteSequence", "'RemoteSequence', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sarona.Models.Abbreviation", b =>
                {
                    b.Property<string>("Abb")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Abb");

                    b.ToTable("Abbreviations");
                });

            modelBuilder.Entity("Sarona.Models.Exchange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abb")
                        .IsRequired();

                    b.Property<int>("Area");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Providence");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("Abb")
                        .IsUnique();

                    b.ToTable("Exchanges");
                });

            modelBuilder.Entity("Sarona.Models.Link", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Channels");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("Direction");

                    b.Property<long>("End1Id");

                    b.Property<long>("End2Id");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<long?>("OtherLinkId");

                    b.Property<string>("Remark");

                    b.Property<int>("Type");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("End1Id");

                    b.HasIndex("End2Id");

                    b.HasIndex("OtherLinkId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Sarona.Models.LinkHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Channels");

                    b.Property<int>("Direction");

                    b.Property<long>("LinkId");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Remark");

                    b.Property<int>("Type");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("LinkId");

                    b.ToTable("LinkHistories");
                });

            modelBuilder.Entity("Sarona.Models.Misc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Miscs");
                });

            modelBuilder.Entity("Sarona.Models.NetworkElement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<long>("ExchangeId");

                    b.Property<int>("InstalledCapacity");

                    b.Property<string>("Manufacturer")
                        .IsRequired();

                    b.Property<string>("Model")
                        .IsRequired();

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name");

                    b.Property<int>("NetworkType");

                    b.Property<string>("Owner")
                        .IsRequired();

                    b.Property<long?>("ParentId");

                    b.Property<string>("Remark");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<int>("UsedCapacity");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("ParentId");

                    b.ToTable("NetworkElements");
                });

            modelBuilder.Entity("Sarona.Models.NumberingPool", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abb");

                    b.Property<int?>("Area");

                    b.Property<string>("ChargingCase")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("ExpireDate");

                    b.Property<bool>("IsFloat");

                    b.Property<bool>("IsKeshvari");

                    b.Property<int?>("Link");

                    b.Property<byte>("Max");

                    b.Property<byte>("Min");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("NumberType")
                        .IsRequired();

                    b.Property<string>("Owner")
                        .IsRequired();

                    b.Property<string>("Prefix")
                        .IsRequired();

                    b.Property<string>("Remark");

                    b.Property<byte>("Rond");

                    b.Property<int?>("SecondaryArea");

                    b.Property<byte>("SecondaryMax");

                    b.Property<byte>("SecondaryMin");

                    b.Property<int>("Status");

                    b.Property<string>("SubscriberName");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("Abb");

                    b.HasIndex("Prefix")
                        .IsUnique();

                    b.ToTable("NumberingPools");
                });

            modelBuilder.Entity("Sarona.Models.NumberingPoolNetworkElement", b =>
                {
                    b.Property<long>("NumberingLocalId");

                    b.Property<long>("NetworkElementId");

                    b.Property<long?>("NumberingId");

                    b.HasKey("NumberingLocalId", "NetworkElementId");

                    b.HasIndex("NetworkElementId");

                    b.HasIndex("NumberingId");

                    b.ToTable("NumberingPoolNetworkElement");
                });

            modelBuilder.Entity("Sarona.Models.Exchange", b =>
                {
                    b.HasOne("Sarona.Models.Abbreviation", "Abbreviation")
                        .WithMany("Exchange")
                        .HasForeignKey("Abb")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sarona.Models.Link", b =>
                {
                    b.HasOne("Sarona.Models.NetworkElement", "End1")
                        .WithMany("LinksOnEnd1")
                        .HasForeignKey("End1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sarona.Models.NetworkElement", "End2")
                        .WithMany("LinksOnEnd2")
                        .HasForeignKey("End2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sarona.Models.Link", "OtherLink")
                        .WithMany()
                        .HasForeignKey("OtherLinkId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sarona.Models.LinkHistory", b =>
                {
                    b.HasOne("Sarona.Models.Link")
                        .WithMany("Histories")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sarona.Models.NetworkElement", b =>
                {
                    b.HasOne("Sarona.Models.Exchange", "Exchange")
                        .WithMany("NetworkElements")
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sarona.Models.NetworkElement", "Parent")
                        .WithMany("NetworkElements")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sarona.Models.NumberingPool", b =>
                {
                    b.HasOne("Sarona.Models.Abbreviation", "Abbreviation")
                        .WithMany("NumbeingPools")
                        .HasForeignKey("Abb")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sarona.Models.NumberingPoolNetworkElement", b =>
                {
                    b.HasOne("Sarona.Models.NetworkElement", "Element")
                        .WithMany("NumberingPoolNetworkElements")
                        .HasForeignKey("NetworkElementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sarona.Models.NumberingPool", "Numbering")
                        .WithMany("NumberingPoolNetworkElements")
                        .HasForeignKey("NumberingId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
